# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
# permalink: /:year-:month-:day-:title/
permalink: /:title/
relative_permalinks: false

# Setup
title:               Les Crapauds Fous
#tagline:             'foo's website
description:         La Fable Moderne d'un Monde Libre et juste un peu Fou
url:                 http://localhost:4000
baseurl:  ""
urlimg: http://localhost:4000/images
markdown: kramdown
paginate: 10
paginate_path: "/textes/page:num"
excerpt_separator: <!--more-->
default_bg: sitelogo.png 
safe: false
#timezone:    America/Chicago
future:      true
github: https://github.com/crazy-toads/crazy-toads.github.io

gems:
  - jekyll-paginate
  - jemoji
  - font-awesome-sass
  - kramdown
  - rouge

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant"]

# About/contact
author:
  name:              Le Crapaud Fou
  url:               https://twitter.com/abcd
  avatar:            crapaud-fou.png
  #email:           

# Owner/author information
owner:
  name:           Le Crapaud Fou
  avatar:         crapaud-fou.png
  #email:          
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  #twitter:        
  #facebook:       
  github:         crazy-toads
  #flickr:

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Accueil
    url: /
  - title: <i class="iconside iconm-user"></i> Cercles
    url: /cercles/
  - title: <i class="iconside iconm-user"></i> Crapauds
    url: /crapauds/
  - title: <i class="iconside iconm-quill"></i> Mare Ã  crapauds
    url: /textes/
  - title: <i class="iconside iconm-user-tie"></i> Partenaires
    url: /partenaires/
  - title: <i class="iconside iconm-user"></i> Nous rejoindre
    url: /contact/
  - title: <i class="iconside iconm-github2"></i> Source
    url: https://github.com/crazy-toads/crazy-toads.github.io
    external: true
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml
  

# Google Custom Search:
#google_search: xyz123abc

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
#twitter_widget_id: xyz123abc

# Add disqus username for Disqus comment board:
# disqus_shortname: foo

# Analytics and webmaster tools stuff goes here
#google_analytics:   xyz123abc

